import express from 'express'; import http from 'http'; import path from 'path'; import {fileURLToPath} from 'url'; import Database from 'better-sqlite3'; import bcrypt from 'bcryptjs'; import jwt from 'jsonwebtoken'; import {WebSocketServer} from 'ws';
const __dirname=path.dirname(fileURLToPath(import.meta.url)),app=express(),server=http.createServer(app),wss=new WebSocketServer({server}),db=new Database('game.db'),SECRET=process.env.JWT_SECRET||'CHANGE_ME';
db.pragma('journal_mode=WAL'); db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password TEXT NOT NULL,gold INTEGER DEFAULT 500,damage INTEGER DEFAULT 100,level INTEGER DEFAULT 1,stage INTEGER DEFAULT 1,xp INTEGER DEFAULT 0,wins INTEGER DEFAULT 0,losses INTEGER DEFAULT 0,rating INTEGER DEFAULT 1000,equipment TEXT DEFAULT '[]',inventory TEXT DEFAULT '[]',created_at INTEGER)`);
const items=[{id:'iron',name:'Espada de Ferro',slot:'arma',rarity:'Comum',power:15},{id:'steel',name:'Espada de Aço',slot:'arma',rarity:'Raro',power:35},{id:'dragon',name:'Lâmina do Dragão',slot:'arma',rarity:'Lendário',power:90},{id:'armor',name:'Armadura Guardiã',slot:'armadura',rarity:'Épico',power:55},{id:'ring',name:'Anel Sombrio',slot:'anel',rarity:'Épico',power:45}];
const pub=u=>({id:u.id,username:u.username,gold:u.gold,damage:u.damage,level:u.level,stage:u.stage,xp:u.xp,wins:u.wins,losses:u.losses,rating:u.rating,equipment:JSON.parse(u.equipment||'[]'),inventory:JSON.parse(u.inventory||'[]')}); const get=id=>db.prepare('SELECT * FROM users WHERE id=?').get(id); const byName=n=>db.prepare('SELECT * FROM users WHERE username=?').get(n);
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),SECRET);next()}catch{res.status(401).json({error:'Não autenticado'})}}
app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
app.post('/api/register',async(req,res)=>{let n=String(req.body.username||'').trim(),p=String(req.body.password||'');if(n.length<3||p.length<4)return res.status(400).json({error:'Usuário 3+ e senha 4+.'});try{let h=await bcrypt.hash(p,10),x=db.prepare('INSERT INTO users(username,password,created_at) VALUES(?,?,?)').run(n,h,Date.now()),u=get(x.lastInsertRowid);res.json({token:jwt.sign({id:u.id,username:n},SECRET),user:pub(u)})}catch{res.status(400).json({error:'Esse usuário já existe.'})}});
app.post('/api/login',async(req,res)=>{let u=byName(String(req.body.username||'')),p=String(req.body.password||'');if(!u||!(await bcrypt.compare(p,u.password)))return res.status(401).json({error:'Login inválido.'});res.json({token:jwt.sign({id:u.id,username:u.username},SECRET),user:pub(u)})});
app.get('/api/me',auth,(req,res)=>res.json(pub(get(req.user.id)))); app.get('/api/items',(req,res)=>res.json(items));
app.post('/api/save',auth,(req,res)=>{let u=get(req.user.id),b=req.body,ks=['gold','damage','level','stage','xp','wins','losses','rating'],v=ks.map(k=>Number.isFinite(Number(b[k]))?Math.max(0,Math.floor(Number(b[k]))):u[k]);db.prepare('UPDATE users SET gold=?,damage=?,level=?,stage=?,xp=?,wins=?,losses=?,rating=?,equipment=?,inventory=? WHERE id=?').run(...v,JSON.stringify(b.equipment||[]),JSON.stringify(b.inventory||[]),u.id);res.json(pub(get(u.id)))});
app.get('/api/ranking',(req,res)=>res.json(db.prepare('SELECT username,level,stage,damage,wins,losses,rating FROM users ORDER BY rating DESC,stage DESC LIMIT 50').all()));
app.post('/api/pvp',auth,(req,res)=>{let me=get(req.user.id),op=db.prepare('SELECT * FROM users WHERE id<>? ORDER BY ABS(rating-?) LIMIT 1').get(me.id,me.rating);if(!op)return res.json({error:'Nenhum adversário cadastrado ainda.'});let win=me.damage+me.level*20+Math.random()*100>=op.damage+op.level*20+Math.random()*100,rr=win?30:-20;db.prepare('UPDATE users SET gold=gold+?,wins=wins+?,losses=losses+?,rating=MAX(0,rating+?) WHERE id=?').run(win?50:15,win?1:0,win?0:1,rr,me.id);db.prepare('UPDATE users SET rating=MAX(0,rating+?) WHERE id=?').run(win?-20:30,op.id);res.json({win,opponent:op.username,reward:win?50:15,rating:rr,user:pub(get(me.id))})});
const clients=new Set();function broadcast(){for(const c of clients)if(c.readyState===1)c.send(JSON.stringify({type:'online',count:clients.size}))} wss.on('connection',ws=>{clients.add(ws);broadcast();ws.on('message',m=>{try{let x=JSON.parse(m);if(x.type==='chat'&&String(x.text||'').trim())for(const c of clients)if(c.readyState===1)c.send(JSON.stringify({type:'chat',user:String(x.user||'Jogador').slice(0,30),text:String(x.text).slice(0,180)}))}catch{}});ws.on('close',()=>{clients.delete(ws);broadcast()})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));server.listen(process.env.PORT||3000,()=>console.log('Idle RPG Online V2 ativo'));
