const express=require('express');const http=require('http');const WebSocket=require('ws');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const fs=require('fs');const path=require('path');
const app=express();const server=http.createServer(app);const wss=new WebSocket.Server({server});
app.use(express.json({limit:'1mb'}));
const DATA=path.join(__dirname,'players.json');const SECRET=process.env.JWT_SECRET||'idle-rpg-v6-secret-change-me';
let players={};try{players=JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{}
function persist(){try{fs.writeFileSync(DATA,JSON.stringify(players,null,2))}catch(e){}}
function clean(p){if(!p)return null;const q={...p};delete q.password;return q}
function auth(req,res,next){try{const h=req.headers.authorization||'';const t=h.replace('Bearer ','');req.user=jwt.verify(t,SECRET);next()}catch{res.status(401).json({error:'Não autorizado'})}}
app.post('/api/register',async(req,res)=>{const username=String(req.body.username||'').trim().slice(0,20);const password=String(req.body.password||'');if(username.length<3||password.length<4)return res.status(400).json({error:'Usuário mínimo 3 e senha mínima 4'});if(players[username])return res.status(409).json({error:'Usuário já existe'});players[username]={username,password:await bcrypt.hash(password,10),level:1,xp:0,gold:500,hero:'Arkan',hp:150,mp:80,inventory:[],equipment:{},skills:{},quests:{slime:0,forest:0,boss:0},wins:0,losses:0,created:Date.now()};persist();res.json({token:jwt.sign({username},SECRET),player:clean(players[username])})});
app.post('/api/login',async(req,res)=>{const username=String(req.body.username||'').trim();const p=players[username];if(!p||!(await bcrypt.compare(String(req.body.password||''),p.password)))return res.status(401).json({error:'Usuário ou senha inválidos'});res.json({token:jwt.sign({username},SECRET),player:clean(p)})});
app.get('/api/player',auth,(req,res)=>res.json(clean(players[req.user.username])));
app.post('/api/save',auth,(req,res)=>{const p=players[req.user.username];if(!p)return res.status(404).end();const b=req.body||{};for(const k of ['level','xp','gold','hero','hp','mp','inventory','equipment','skills','quests','wins','losses'])if(b[k]!==undefined)p[k]=b[k];persist();res.json({ok:true,player:clean(p)})});
app.get('/api/ranking',(req,res)=>res.json(Object.values(players).map(clean).sort((a,b)=>b.level-a.level||b.xp-a.xp||b.wins-a.wins).slice(0,30)));
app.get('/api/health',(req,res)=>res.json({ok:true,version:'13.0.0',online:wss.clients.size}));
app.get(/.*/,(req,res)=>res.sendFile(path.join(__dirname,'index.html')));
const online=new Map();function broadcast(obj,except){const s=JSON.stringify(obj);for(const c of wss.clients)if(c!==except&&c.readyState===WebSocket.OPEN)c.send(s)}
wss.on('connection',ws=>{let name='Anônimo';ws.on('message',raw=>{try{const m=JSON.parse(raw);if(m.type==='join'){name=String(m.name||'Anônimo').slice(0,20);online.set(ws,{name,x:Number(m.x)||0,y:Number(m.y)||0,hero:String(m.hero||'Arkan')});broadcast({type:'online',count:wss.clients.size,players:[...online.values()]})}else if(m.type==='pos'){const o=online.get(ws);if(o){o.x=Number(m.x)||0;o.y=Number(m.y)||0;o.hero=String(m.hero||o.hero);broadcast({type:'pos',name:o.name,x:o.x,y:o.y,hero:o.hero},ws)}}else if(m.type==='chat'){const text=String(m.text||'').trim().slice(0,180);if(text)broadcast({type:'chat',name,text},null)}}catch{}});ws.on('close',()=>{online.delete(ws);broadcast({type:'online',count:wss.clients.size,players:[...online.values()]})})});
const PORT=Number(process.env.PORT||3000);server.listen(PORT,'0.0.0.0',()=>console.log('Idle RPG Online V13 ativo na porta '+PORT));
